apiVersion: apps/v1
kind: Deployment
metadata:
  name: earphones-deployment
  labels:
    app: earphones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: earphones
  template:
    metadata:
      labels:
        app: earphones
    spec:
      containers:
      - name: earphones
        image: 747917427963.dkr.ecr.us-east-1.amazonaws.com/shopping-site-earphones:0f44f3f0ab1d3716765a5643e5f4223dbeac248b
        ports:
        - containerPort: 80
