apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: 747917427963.dkr.ecr.us-east-1.amazonaws.com/shopping-site-backend:33ff6216b15c747167cd30465a8c82816ea16322
          ports:
            - containerPort: 5000
