apiVersion: apps/v1
kind: Deployment
metadata:
  name: phones-deployment
  labels:
    app: phones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phones
  template:
    metadata:
      labels:
        app: phones
    spec:
      containers:
      - name: phones
        image: 747917427963.dkr.ecr.us-east-1.amazonaws.com/shopping-site-phones:0f44f3f0ab1d3716765a5643e5f4223dbeac248b
        ports:
        - containerPort: 80
